### PR TITLE
Update the     README.md file to describe the     repo.

### PR DESCRIPTION
**Pull request by KaitlynND**
Portfolio

### CODE REVIEW

**Comment by aychin** [comment]
Nice first PR!

**Comment by aychin** [comment]
I wanted to approve, but I don't see a button anywhere. I think I might need to have write access to the repo based on your constraints:

Review required
At least 1 approving review is required by reviewers with write access. 
Merging is blocked
Merging can be performed automatically with 1 approving review.

**Comment by KaitlynND** [comment]
So is there anything I have to do in order for you to approve?

Sent from my iPhone

On Jun 8, 2020, at 2:38 AM, aychin <notifications@github.com> wrote:

﻿

I wanted to approve, but I don't see a button anywhere. I think I might need to have write access to the repo based on your constraints:

Review required
At least 1 approving review is required by reviewers with write access.
Merging is blocked
Merging can be performed automatically with 1 approving review.

**Comment by aychin** [comment]
Picking this up again from the chat. Let's see if we can get your change merged. I think one of two things needs to happen:
* add me (and zhaonian) with write access to your repo
* change the branch protection rules so that write access is not required to approve a review

I think the first one is likely the way to go; I'm not sure how to do it off the top of my head though.

I found some docs which may be of help (you can also feel free to ask TCs):
https://help.github.com/en/github/administering-a-repository/about-required-reviews-for-pull-requests
https://help.github.com/en/enterprise/2.15/user/articles/adding-outside-collaborators-to-repositories-in-your-organization (Ctrl+F "write")

**Review by zhaonian — APPROVED** [review]
🎉

**Review by aychin — APPROVED** [review]

**Pull request closed without merging**
